/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package application;

import model.Labyrinth;

import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class App {

   public static void main(String[] args) {
      Scanner input = null;
      try {
         input = new Scanner(Path.of(App.class.getClassLoader().getResource("ascii_path_5.txt").toURI()))
               .useDelimiter("\n");
      } catch (Exception e) {
         e.printStackTrace();
      }

      List<String> lines = new ArrayList<>();
      while (input != null && input.hasNext()) {
         lines.add(input.next());
      }

      Labyrinth labyrinth = new Labyrinth(lines);

      while (labyrinth.nextMove()) {
         System.out.println(labyrinth.getFullPath());
      }

      System.out.println(labyrinth.getFullPath());
   }
}
